-- Cart-level promotion rules, such as "1+1=3" for disposable products.
-- Run once after the base catalog schema is applied.

create table if not exists public.promotion_rules (
  id bigint generated by default as identity primary key,
  city_id bigint null references public.cities (id) on delete cascade,
  type text not null,
  title text not null,
  category_slug text not null default 'disposable',
  brand text null,
  starts_at timestamptz null,
  ends_at timestamptz null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (type in ('buy_2_get_3_cheapest_free')),
  check (category_slug <> ''),
  check (ends_at is null or starts_at is null or ends_at >= starts_at)
);

alter table public.orders
  add column if not exists promotion_discount_amount numeric not null default 0;

alter table public.promotion_rules
  add column if not exists city_id bigint null references public.cities (id) on delete cascade;

drop index if exists public.promotion_rules_active_window_idx;

create index if not exists promotion_rules_active_window_idx
  on public.promotion_rules (city_id, is_active, starts_at, ends_at, id);

revoke all on public.promotion_rules from anon, authenticated;

alter table public.promotion_rules enable row level security;

drop policy if exists "Public read active promotion rules" on public.promotion_rules;

notify pgrst, 'reload schema';
