-- Referral + points ledger extensions
-- Run this after referral tables migration

alter table public.customer_profiles
  add column if not exists tg_username text;

create table if not exists public.loyalty_transactions (
  id bigint generated by default as identity primary key,
  tg_user_id bigint not null references public.customer_profiles (tg_user_id) on delete cascade,
  delta_points int not null,
  kind text not null,
  referral_id bigint null references public.referrals (id) on delete set null,
  order_id uuid null references public.orders (id) on delete set null,
  created_at timestamptz not null default now()
);

-- Prevent duplicate referral rewards for the same user/referral pair.
create unique index if not exists loyalty_referral_bonus_unique_idx
  on public.loyalty_transactions (tg_user_id, kind, referral_id)
  where referral_id is not null
    and kind in ('referral_inviter_bonus', 'referral_invitee_bonus');

-- Prevent duplicate points write-off for the same order.
create unique index if not exists loyalty_order_points_spend_unique_idx
  on public.loyalty_transactions (tg_user_id, kind, order_id)
  where order_id is not null
    and kind = 'order_points_spend';

create index if not exists loyalty_transactions_user_created_idx
  on public.loyalty_transactions (tg_user_id, created_at desc);

create index if not exists loyalty_transactions_referral_idx
  on public.loyalty_transactions (referral_id);

create index if not exists loyalty_transactions_order_idx
  on public.loyalty_transactions (order_id);

create index if not exists referrals_inviter_created_idx
  on public.referrals (inviter_tg_user_id, created_at desc);

alter table public.loyalty_transactions enable row level security;
revoke all on public.loyalty_transactions from anon, authenticated;

notify pgrst, 'reload schema';
