-- Promo products per city.
-- Run once after the base catalog schema is applied.

create table if not exists public.promo_products (
  id bigint generated by default as identity primary key,
  city_id bigint not null references public.cities (id) on delete cascade,
  product_id uuid not null references public.products (id) on delete cascade,
  old_price numeric not null,
  new_price numeric not null,
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (city_id, product_id),
  check (old_price >= 0),
  check (new_price >= 0)
);

create index if not exists promo_products_city_active_sort_idx
  on public.promo_products (city_id, is_active, sort_order, id);

create index if not exists promo_products_product_idx
  on public.promo_products (product_id);

-- Promo rows stay server-readable; active promos are exposed through backend catalog API.
revoke all on public.promo_products from anon, authenticated;

alter table public.promo_products enable row level security;

drop policy if exists "Public read active promo products" on public.promo_products;

notify pgrst, 'reload schema';
