-- Per-staff stock, sale attribution and non-sale inventory operations.
-- Run once on existing deployments after the base schema.

create table if not exists public.staff_members (
  id bigint generated by default as identity primary key,
  name text not null check (btrim(name) <> ''),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.staff_inventory (
  id bigint generated by default as identity primary key,
  staff_id bigint not null references public.staff_members (id) on delete cascade,
  city_id bigint not null references public.cities (id) on delete cascade,
  product_id uuid not null references public.products (id) on delete cascade,
  stock_qty int not null default 0 check (stock_qty >= 0),
  unique (staff_id, city_id, product_id)
);

alter table public.orders
  add column if not exists seller_id bigint references public.staff_members (id) on delete set null;

alter table public.orders
  add column if not exists payment_method text;

alter table public.orders
  drop constraint if exists orders_payment_method_check;

alter table public.orders
  add constraint orders_payment_method_check
  check (payment_method is null or payment_method in ('cash', 'card'));

create table if not exists public.inventory_movements (
  id bigint generated by default as identity primary key,
  city_id bigint not null references public.cities (id) on delete cascade,
  staff_id bigint references public.staff_members (id) on delete set null,
  product_id uuid not null references public.products (id) on delete restrict,
  kind text not null check (kind in ('sale', 'defect', 'replacement')),
  qty int not null check (qty > 0),
  related_product_id uuid references public.products (id) on delete restrict,
  order_id uuid references public.orders (id) on delete set null,
  note text null,
  created_at timestamptz not null default now()
);

create index if not exists staff_inventory_city_staff_product_idx
  on public.staff_inventory (city_id, staff_id, product_id);

create index if not exists inventory_movements_city_created_at_idx
  on public.inventory_movements (city_id, created_at desc);

alter table public.staff_members enable row level security;
alter table public.staff_inventory enable row level security;
alter table public.inventory_movements enable row level security;

revoke all on public.staff_members from anon, authenticated;
revoke all on public.staff_inventory from anon, authenticated;
revoke all on public.inventory_movements from anon, authenticated;

-- Restore points for product imports and image uploads. The backend service role
-- is the only actor that can access them; the API additionally checks the owner TG id.
create table if not exists public.admin_change_versions (
  id uuid primary key default gen_random_uuid(),
  kind text not null check (kind in ('products', 'images')),
  city_slug text null,
  label text not null,
  snapshot jsonb not null,
  created_by_tg_user_id bigint not null,
  created_at timestamptz not null default now()
);

create index if not exists admin_change_versions_kind_created_at_idx
  on public.admin_change_versions (kind, created_at desc);

alter table public.admin_change_versions enable row level security;
revoke all on public.admin_change_versions from anon, authenticated;
