-- Supabase MVP schema for Telegram Mini App
-- Notes:
-- - Orders will be created by a future backend using the service_role key.
-- - Therefore we ENABLE RLS everywhere, but ONLY create public SELECT policies
--   for cities/products/inventory. No public access to orders/order_items/admins.

create extension if not exists pgcrypto;

-- ===== Tables =====

create table if not exists public.cities (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  base_price numeric not null,
  image_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.inventory (
  id bigint generated by default as identity primary key,
  product_id uuid not null references public.products (id) on delete cascade,
  city_id bigint not null references public.cities (id) on delete cascade,
  in_stock boolean not null default false,
  stock_qty int null,
  price_override numeric null,
  unique (product_id, city_id)
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  tg_user_id bigint not null,
  tg_username text null,
  city_id bigint references public.cities (id),
  delivery_method text not null,
  comment text null,
  status text not null default 'new',
  total_price numeric not null,
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders (id) on delete cascade,
  product_id uuid references public.products (id),
  qty int not null,
  unit_price numeric not null
);

create table if not exists public.admins (
  tg_user_id bigint primary key,
  role text not null default 'manager'
);

-- ===== Indexes =====

create index if not exists inventory_city_product_idx
  on public.inventory (city_id, product_id);

create index if not exists products_is_active_idx
  on public.products (is_active);

-- ===== RLS =====

alter table public.cities enable row level security;
alter table public.products enable row level security;
alter table public.inventory enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.admins enable row level security;

-- ===== Policies (public read-only catalog) =====

drop policy if exists "Public read cities" on public.cities;
create policy "Public read cities"
  on public.cities
  for select
  to anon, authenticated
  using (true);

drop policy if exists "Public read active products" on public.products;
create policy "Public read active products"
  on public.products
  for select
  to anon, authenticated
  using (is_active = true);

drop policy if exists "Public read inventory for active products" on public.inventory;
create policy "Public read inventory for active products"
  on public.inventory
  for select
  to anon, authenticated
  using (
    exists (
      select 1
      from public.products p
      where p.id = inventory.product_id
        and p.is_active = true
    )
  );

-- IMPORTANT:
-- - orders/order_items/admins have RLS enabled and NO public policies.
-- - Use service_role from backend to create/manage orders.

-- ===== Optional: Storage policy (public read for product-images) =====
-- Supabase projects include the storage schema by default, but this block is guarded
-- so schema.sql won't fail if storage is unavailable for any reason.
do $$
begin
  if to_regclass('storage.objects') is null then
    raise notice 'storage.objects not found, skipping storage policies';
    return;
  end if;

  alter table storage.objects enable row level security;

  drop policy if exists "Public read product images" on storage.objects;
  create policy "Public read product images"
    on storage.objects
    for select
    to anon, authenticated
    using (bucket_id = 'product-images');
exception
  when insufficient_privilege then
    raise notice 'insufficient_privilege to manage storage policies, skipping';
end $$;

