-- Supabase MVP schema for Telegram Mini App
-- Notes:
-- - Orders will be created by a future backend using the service_role key.
-- - Therefore we ENABLE RLS everywhere, but ONLY create public SELECT policies
--   for cities/products/inventory. No public access to orders/order_items/admins.

create extension if not exists pgcrypto;

-- ===== Tables =====

create table if not exists public.cities (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  category_slug text not null default 'other',
  base_price numeric not null,
  image_url text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

-- Backward-compatible patch for existing DBs:
-- ensures category column exists and is populated.
alter table public.products
  add column if not exists category_slug text;

update public.products
set category_slug = 'other'
where category_slug is null
   or btrim(category_slug) = '';

alter table public.products
  alter column category_slug set default 'other';

alter table public.products
  alter column category_slug set not null;

create table if not exists public.inventory (
  id bigint generated by default as identity primary key,
  product_id uuid not null references public.products (id) on delete cascade,
  city_id bigint not null references public.cities (id) on delete cascade,
  in_stock boolean not null default false,
  stock_qty int null,
  price_override numeric null,
  unique (product_id, city_id)
);

create table if not exists public.promo_products (
  id bigint generated by default as identity primary key,
  city_id bigint not null references public.cities (id) on delete cascade,
  product_id uuid not null references public.products (id) on delete cascade,
  old_price numeric not null,
  new_price numeric not null,
  sort_order int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (city_id, product_id),
  check (old_price >= 0),
  check (new_price >= 0)
);

create table if not exists public.promotion_rules (
  id bigint generated by default as identity primary key,
  city_id bigint null references public.cities (id) on delete cascade,
  type text not null,
  title text not null,
  category_slug text not null default 'disposable',
  brand text null,
  product_ids uuid[] null,
  starts_at timestamptz null,
  ends_at timestamptz null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint promotion_rules_type_check
    check (type in ('buy_2_get_3_cheapest_free', 'buy_pod_get_liquid_cheapest_free')),
  constraint promotion_rules_product_ids_check
    check (product_ids is null or (type = 'buy_2_get_3_cheapest_free' and cardinality(product_ids) > 0)),
  check (category_slug <> ''),
  check (ends_at is null or starts_at is null or ends_at >= starts_at)
);

create table if not exists public.promo_codes (
  code text primary key,
  discount_amount numeric not null,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  max_uses int not null,
  used_count int not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (btrim(code) <> ''),
  check (discount_amount > 0),
  check (max_uses > 0),
  check (used_count >= 0),
  check (used_count <= max_uses),
  check (ends_at >= starts_at)
);

create table if not exists public.delivery_pricing_settings (
  city_slug text primary key,
  base_fee_rub numeric not null default 150,
  rules jsonb not null default '[]'::jsonb,
  peak_surcharge_rules jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (city_slug in ('vvo', 'blg')),
  check (base_fee_rub >= 0 and base_fee_rub <= 10000),
  check (jsonb_typeof(rules) = 'array'),
  check (jsonb_typeof(peak_surcharge_rules) = 'array')
);

insert into public.delivery_pricing_settings (city_slug, base_fee_rub, rules)
values ('blg', 150, '[]'::jsonb)
on conflict (city_slug) do nothing;

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  tg_user_id bigint not null,
  tg_username text null,
  city_id bigint references public.cities (id),
  delivery_method text not null,
  comment text null,
  status text not null default 'new',
  total_price numeric not null,
  total_before_discount numeric null,
  promotion_discount_amount numeric not null default 0,
  discount_amount numeric not null default 0,
  total_after_discount numeric null,
  notify_chat_id bigint null,
  notify_message_id bigint null,
  notify_sent_at timestamptz null,
  notify_targets jsonb not null default '[]'::jsonb,
  coupon_id text null,
  coupon_discount_amount numeric not null default 0,
  edited_at timestamptz null,
  edit_session_expires_at timestamptz null,
  created_at timestamptz not null default now()
);

-- Backward-compatible patch for order statuses:
-- some deployed DBs still have an older constraint without 'cancelled'.
alter table public.orders
  drop constraint if exists orders_status_check;

alter table public.orders
  add constraint orders_status_check
  check (status in ('new', 'processing', 'done', 'cancelled'));

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders (id) on delete cascade,
  product_id uuid references public.products (id),
  qty int not null,
  unit_price numeric not null
);

create table if not exists public.admins (
  tg_user_id bigint primary key,
  role text not null default 'manager'
);

-- ===== Indexes =====

create index if not exists inventory_city_product_idx
  on public.inventory (city_id, product_id);

create index if not exists products_is_active_idx
  on public.products (is_active);

create index if not exists products_category_slug_idx
  on public.products (category_slug);

create index if not exists promo_products_city_active_sort_idx
  on public.promo_products (city_id, is_active, sort_order, id);

create index if not exists promo_products_product_idx
  on public.promo_products (product_id);

create index if not exists promotion_rules_active_window_idx
  on public.promotion_rules (city_id, is_active, starts_at, ends_at, id);

create index if not exists promo_codes_active_window_idx
  on public.promo_codes (is_active, starts_at, ends_at, code);

create index if not exists orders_status_created_at_idx
  on public.orders (status, created_at desc);

create index if not exists orders_coupon_id_idx
  on public.orders (coupon_id)
  where coupon_id is not null;

create index if not exists order_items_order_id_idx
  on public.order_items (order_id);

-- ===== Grants (PostgREST roles) =====
-- Supabase обычно настраивает default privileges, но явные GRANT делают поведение предсказуемым:
-- anon/authenticated могут только читать публичный каталог (cities/products/inventory).
grant usage on schema public to anon, authenticated;
grant select on public.cities to anon, authenticated;
grant select on public.products to anon, authenticated;
grant select on public.inventory to anon, authenticated;
revoke all on public.promo_products from anon, authenticated;
revoke all on public.promotion_rules from anon, authenticated;
revoke all on public.promo_codes from anon, authenticated;
revoke all on public.delivery_pricing_settings from anon, authenticated;

-- ===== RLS =====

alter table public.cities enable row level security;
alter table public.products enable row level security;
alter table public.inventory enable row level security;
alter table public.promo_products enable row level security;
alter table public.promotion_rules enable row level security;
alter table public.promo_codes enable row level security;
alter table public.delivery_pricing_settings enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.admins enable row level security;

-- ===== Policies (public read-only catalog) =====

drop policy if exists "Public read cities" on public.cities;
create policy "Public read cities"
  on public.cities
  for select
  to anon, authenticated
  using (true);

drop policy if exists "Public read active products" on public.products;
create policy "Public read active products"
  on public.products
  for select
  to anon, authenticated
  using (is_active = true);

drop policy if exists "Public read inventory for active products" on public.inventory;
create policy "Public read inventory for active products"
  on public.inventory
  for select
  to anon, authenticated
  using (
    exists (
      select 1
      from public.products p
      where p.id = inventory.product_id
        and p.is_active = true
    )
  );

drop policy if exists "Public read active promo products" on public.promo_products;
drop policy if exists "Public read active promotion rules" on public.promotion_rules;

-- IMPORTANT:
-- - promotion_rules/orders/order_items/admins have RLS enabled and NO public policies.
-- - Use service_role from backend to create/manage orders.

-- ===== Optional: Storage policy (public read for product-images) =====
-- Supabase projects include the storage schema by default, but this block is guarded
-- so schema.sql won't fail if storage is unavailable for any reason.
do $$
begin
  if to_regclass('storage.objects') is null then
    raise notice 'storage.objects not found, skipping storage policies';
    return;
  end if;

  alter table storage.objects enable row level security;

  drop policy if exists "Public read product images" on storage.objects;
  create policy "Public read product images"
    on storage.objects
    for select
    to anon, authenticated
    using (bucket_id = 'product-images');
exception
  when insufficient_privilege then
    raise notice 'insufficient_privilege to manage storage policies, skipping';
end $$;
